### ISSUE TITLE
海康录像机 设备名称中文乱码

### ISSUE THREAD

**Issue by XJain01** [ossrs/srs-gb28181#33]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716
![image](https://user-images.githubusercontent.com/80761980/148336857-c265acfc-cedf-4a2c-bafb-a519dab6ccae.png)

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `xxxxxx`

1. SRS的日志如下(Log):
```

xxxxxxxxxxxx

```

1. SRS的配置如下(Config):
```

xxxxxxxxxxxx

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

由于265主要在GB中使用，所以265分支也迁移到了 [srs-gb28181](https://github.com/ossrs/srs-gb28181/tree/feature/h265)

该Issue会被删除，请先阅读FAQ：#2716

**Comment by duiniuluantanqin** [comment]
自己转吧

**Comment by winlinvip** [comment]
GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

由于265主要在GB中使用，所以265分支也迁移到了 [srs-gb28181](https://github.com/ossrs/srs-gb28181/tree/feature/h265)

该Issue会被删除，请先阅读FAQ：#2716

**Comment by bigbeer1** [comment]
自己转UTF-8，默认是GB3121我记得是
