### ISSUE TITLE
srs接入GB28181协议的布控球摄像头，30台设备以上，现在设备上线后，经常导致srs服务器退出停止，可以怎么处理吗

### ISSUE THREAD

**Issue by FutureComeIn** [ossrs/srs-gb28181#34]
SRS版本(Version): 4.0
SRS的日志如下(Log):
SRS的配置如下(Config):

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
daemon              on;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

stats {
    network         0;
}

stream_caster {
    enabled             on;
    caster              gb28181;
    output              rtmp://127.0.0.1:1935/live/[stream];
    
    listen              9000;
	
    tcp_enable            on;

    rtp_port_min        58200;

    rtp_port_max        58300;

    wait_keyframe       on;
    
    rtp_idle_timeout    30;

    audio_enable        off;

    jitterbuffer_enable  off;

    host       192.168.1.5;

    auto_create_channel   off;

    sip {
        enabled on;

        listen              5060;
        
        serial              34020000002000000001;

        realm               3402000000;

        ack_timeout         30;

        keepalive_timeout   120;

        auto_play           on;
		
        invite_port_fixed     on;

        query_catalog_interval  60;
    }
}

rtc_server {
    enabled         on;
    
    listen          8000;

    candidate       192.168.1.5;
}

vhost __defaultVhost__ {
    
    rtc {
        enabled     on;
        bframe      discard;
    }
    
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
    }
    
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

**Comment by duiniuluantanqin** [comment]
日志有吗？core文件有吗？自己先用gdb调试core文件看看能不能定位问题？
gb的问题要靠我们自力更生了兄弟，搞起来呀。

**Comment by FutureComeIn** [comment]
> 日志有吗？core文件有吗？自己先用gdb调试core文件看看能不能定位问题？ gb的问题要靠我们自力更生了兄弟，搞起来呀。

问题应该是知道， srs拉某个设备的流时提示 is busy，百度搜了下：srs现在有个bug，当不能拉流，kill调它时，srs会重启，有没有项目中也遇到过这种问题的，能怎么解决
错误日志：指向源码的do_cycle()
![log](https://user-images.githubusercontent.com/64940184/148868075-425d76d3-9dd8-4a32-abd4-22a49c00c52c.png)
